---
name: ColorfulChat
version: 1.0.0
main: santana\colorful\ColorfulChat
api: [ 4.0.0 ]
author: Santana#9999
description: A Chat Color Personlization Plugin for Minecraft Bedrock Edition
permissions:
  colorfulchat.command.use:
    default: false
...
